# Generated by Django 5.1.6 on 2025-02-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_tag_project_category_project_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='written_by',
        ),
    ]
